"use client";

import { useState } from "react";
import { useVerifyCertificateBySlNo } from "../hooks/useverifycertificate";
import { CertificateWithId } from "../types/verify-certificate.types";
import type { Timestamp } from "firebase/firestore";

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatTimestamp(ts: Timestamp | undefined): string {
  if (!ts) return "—";
  return ts.toDate().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function formatDate(dateStr: string | undefined): string {
  if (!dateStr) return "—";
  try {
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return dateStr;
    return d.toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  } catch {
    return dateStr;
  }
}

function escapeHtml(str: string | number | undefined | null): string {
  if (str === undefined || str === null) return "—";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// ─── Icons ──────────────────────────────────────────────────────────────────

function IconShieldCheck() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M12 2.75l7.5 2.625v6.375c0 4.5-3.15 8.55-7.5 9.75-4.35-1.2-7.5-5.25-7.5-9.75V5.375L12 2.75z"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M9 12.25l2 2 4.25-4.25"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function IconSearch() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <circle cx="11" cy="11" r="7" stroke="currentColor" strokeWidth="2" />
      <path d="M20 20l-3.5-3.5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
    </svg>
  );
}

function IconDownload() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M12 3v12m0 0l-4-4m4 4l4-4M5 21h14"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

// ─── Sub-components ──────────────────────────────────────────────────────────

function InfoRow({
  label,
  value,
  highlight = false,
}: {
  label: string;
  value: string;
  highlight?: boolean;
}) {
  return (
    <div className="ek-info-row">
      <span className="ek-info-label">{label}</span>
      <span className={`ek-info-value${highlight ? " ek-info-value--hl" : ""}`}>
        {value}
      </span>
    </div>
  );
}

function CertificateCard({ cert }: { cert: CertificateWithId }) {
  const statusText = cert.status
    ? cert.status.charAt(0).toUpperCase() + cert.status.slice(1)
    : "Generated";

  return (
    <article className="ek-cert-card">
      {/* Header */}
      <header className="ek-cert-header">
        <div className="ek-cert-header-left">
          <span className="ek-cert-badge-icon">
            <IconShieldCheck />
          </span>
          <span className="ek-cert-header-title">Verified Certificate</span>
        </div>
        <div className="ek-cert-serial">{escapeHtml(cert.slNo)}</div>
      </header>

      {/* Hero */}
      <section className="ek-cert-hero">
        <p className="ek-cert-hero-eyebrow">This certifies that</p>
        <h2 className="ek-cert-hero-name">{escapeHtml(cert.name)}</h2>
        <p className="ek-cert-hero-sub">
          {escapeHtml(cert.studyingIn)} · {escapeHtml(cert.college)}
        </p>
      </section>

      <div className="ek-cert-divider" />

      {/* Info grid */}
      <section className="ek-cert-info">
        <InfoRow label="Field / Domain" value={escapeHtml(cert.field)} highlight />
        <InfoRow label="Training Mode" value={escapeHtml(cert.trainingMode)} />
        <InfoRow
          label="Period"
          value={`${formatDate(cert.periodFrom)} — ${formatDate(cert.periodTo)}`}
        />
        <InfoRow label="Issue Date" value={formatDate(cert.date)} />
        <InfoRow
          label="Attendance"
          value={`${escapeHtml(cert.attendance)}%`}
          highlight
        />
        <InfoRow
          label="Performance"
          value={`${escapeHtml(cert.performance)}%`}
          highlight
        />
        <InfoRow label="Generated By" value={escapeHtml(cert.generatedBy)} />
        <InfoRow label="Last Updated" value={formatTimestamp(cert.lastUpdated)} />
      </section>

      {/* Footer */}
      <footer className="ek-cert-footer">
        <div className="ek-status-chip">
          <span className="ek-status-dot" />
          {escapeHtml(statusText)}
        </div>

        {cert.pdfUrl && (
          <a
            href={cert.pdfUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="ek-btn-download"
          >
            <IconDownload />
            Download Certificate
          </a>
        )}
      </footer>
    </article>
  );
}

// ─── Main Page ───────────────────────────────────────────────────────────────

export default function VerifyCertificatePage() {
  const [inputValue, setInputValue] = useState("");
  const [submittedSlNo, setSubmittedSlNo] = useState<string | null>(null);

  const { certificate, loading, error } =
    useVerifyCertificateBySlNo(submittedSlNo);

  function handleVerify() {
    const trimmed = inputValue.trim();
    if (!trimmed) return;
    setSubmittedSlNo(trimmed);
  }

  function handleReset() {
    setInputValue("");
    setSubmittedSlNo(null);
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") {
      e.preventDefault();
      handleVerify();
    }
  }

  return (
    <>
      <style>{`
        /* ─── EzyKnot Careers · Brand-Matched Theme ─────────────────── */
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Inter:wght@400;500;600&display=swap');

        .ek-root *,
        .ek-root *::before,
        .ek-root *::after {
          box-sizing: border-box;
          margin: 0;
          padding: 0;
        }

        .ek-root {
          /* ── Brand colors extracted from logo ── */
          --ek-navy: #1E3A6E;         /* deep navy blue from "Ezy" text */
          --ek-navy-dark: #142a52;
          --ek-navy-light: #2d4d85;
          --ek-orange: #F7941E;        /* vibrant orange from "Knot" text */
          --ek-orange-dark: #d97b0a;
          --ek-orange-light: #FBB040;  /* warm gold from arrow tip */
          --ek-green: #7AB947;         /* green from arrow */
          --ek-blue: #1B75BC;          /* blue from arrow swirl */

          --ek-bg: #f7f9fc;
          --ek-bg-2: #eef3f9;
          --ek-surface: #ffffff;
          --ek-surface-2: #fafbfd;

          --ek-text: #0f1e35;
          --ek-text-2: #2c3e5c;
          --ek-text-mute: #6b7c94;

          --ek-border: #e1e8f0;
          --ek-border-2: #d0dae6;

          --ek-success: #16a34a;
          --ek-success-bg: #dcfce7;
          --ek-error: #dc2626;
          --ek-error-bg: #fef2f2;

          --ek-radius-sm: 8px;
          --ek-radius-md: 12px;
          --ek-radius-lg: 16px;
          --ek-radius-xl: 24px;

          --ek-shadow-sm: 0 1px 2px rgba(15, 30, 53, 0.04);
          --ek-shadow-md: 0 4px 12px rgba(15, 30, 53, 0.06), 0 1px 3px rgba(15, 30, 53, 0.04);
          --ek-shadow-lg: 0 12px 32px rgba(15, 30, 53, 0.08), 0 2px 6px rgba(15, 30, 53, 0.04);
          --ek-shadow-xl: 0 24px 60px rgba(15, 30, 53, 0.10), 0 6px 16px rgba(15, 30, 53, 0.05);

          --ek-font-display: 'Plus Jakarta Sans', system-ui, sans-serif;
          --ek-font-body: 'Inter', system-ui, sans-serif;

          position: relative;
          min-height: 100vh;
          background: var(--ek-bg);
          color: var(--ek-text);
          font-family: var(--ek-font-body);
          line-height: 1.5;
          overflow-x: hidden;
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
        }

        /* Decorative brand-tinted background */
        .ek-root::before {
          content: '';
          position: fixed;
          inset: 0;
          background:
            radial-gradient(circle at 10% 5%, rgba(247, 148, 30, 0.08), transparent 42%),
            radial-gradient(circle at 90% 8%, rgba(30, 58, 110, 0.07), transparent 45%),
            radial-gradient(circle at 50% 105%, rgba(27, 117, 188, 0.05), transparent 55%);
          pointer-events: none;
          z-index: 0;
        }

        .ek-shell {
          position: relative;
          z-index: 1;
          min-height: 100vh;
          display: flex;
          flex-direction: column;
          align-items: center;
          padding: 40px 20px 72px;
        }

        .ek-container {
          width: 100%;
          max-width: 620px;
          display: flex;
          flex-direction: column;
          gap: 32px;
        }

        /* ─── Brand header with logo ─────────────────────────────── */
        .ek-brand {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 14px;
          text-align: center;
          animation: ekFadeUp 0.55s cubic-bezier(0.16, 1, 0.3, 1) both;
        }

        .ek-logo {
          display: flex;
          align-items: center;
          gap: 14px;
          padding: 12px 22px;
          background: white;
          border: 1px solid var(--ek-border);
          border-radius: 100px;
          box-shadow: var(--ek-shadow-md);
        }

        .ek-logo-mark {
          position: relative;
          width: 42px;
          height: 42px;
          flex-shrink: 0;
        }

        .ek-logo-mark svg {
          width: 100%;
          height: 100%;
          display: block;
        }

        .ek-logo-text {
          display: flex;
          flex-direction: column;
          align-items: flex-start;
          line-height: 1;
          gap: 3px;
        }

        .ek-logo-name {
          font-family: var(--ek-font-display);
          font-size: 20px;
          font-weight: 800;
          letter-spacing: -0.02em;
          color: var(--ek-navy);
        }

        .ek-logo-name .ek-logo-knot {
          color: var(--ek-orange);
        }

        .ek-logo-sub {
          display: flex;
          align-items: center;
          gap: 8px;
          font-family: var(--ek-font-display);
          font-size: 11px;
          font-weight: 600;
          letter-spacing: 0.28em;
          text-transform: uppercase;
          color: var(--ek-navy);
          padding-left: 2px;
        }

        .ek-logo-sub::before,
        .ek-logo-sub::after {
          content: '';
          width: 16px;
          height: 1.5px;
          background: var(--ek-navy);
          opacity: 0.5;
        }

        /* ─── Hero ─────────────────────────────────────────────────── */
        .ek-hero {
          text-align: center;
          animation: ekFadeUp 0.55s 0.06s cubic-bezier(0.16, 1, 0.3, 1) both;
        }

        .ek-hero h1 {
          font-family: var(--ek-font-display);
          font-size: clamp(32px, 6.5vw, 48px);
          font-weight: 800;
          line-height: 1.1;
          letter-spacing: -0.03em;
          color: var(--ek-navy);
          margin-bottom: 12px;
        }

        .ek-hero h1 em {
          font-style: normal;
          background: linear-gradient(135deg, var(--ek-orange) 0%, var(--ek-orange-light) 100%);
          -webkit-background-clip: text;
          background-clip: text;
          -webkit-text-fill-color: transparent;
          color: transparent;
        }

        .ek-hero p {
          font-size: 15px;
          color: var(--ek-text-mute);
          max-width: 460px;
          margin: 0 auto;
          line-height: 1.65;
          font-weight: 400;
        }

        /* ─── Search panel ─────────────────────────────────────────── */
        .ek-search {
          position: relative;
          background: var(--ek-surface);
          border: 1px solid var(--ek-border);
          border-radius: var(--ek-radius-xl);
          padding: 28px;
          box-shadow: var(--ek-shadow-lg);
          display: flex;
          flex-direction: column;
          gap: 14px;
          animation: ekFadeUp 0.55s 0.12s cubic-bezier(0.16, 1, 0.3, 1) both;
          overflow: hidden;
        }

        .ek-search::before {
          content: '';
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          height: 3px;
          background: linear-gradient(90deg, var(--ek-navy) 0%, var(--ek-orange) 50%, var(--ek-orange-light) 100%);
        }

        .ek-search-label {
          display: block;
          font-size: 11px;
          font-weight: 700;
          letter-spacing: 0.14em;
          text-transform: uppercase;
          color: var(--ek-navy);
        }

        .ek-search-row {
          display: flex;
          gap: 10px;
        }

        .ek-input-wrap {
          position: relative;
          flex: 1;
          min-width: 0;
        }

        .ek-input-icon {
          position: absolute;
          left: 16px;
          top: 50%;
          transform: translateY(-50%);
          color: var(--ek-text-mute);
          pointer-events: none;
          display: flex;
        }

        .ek-search-input {
          width: 100%;
          padding: 14px 16px 14px 44px;
          border: 1.5px solid var(--ek-border-2);
          border-radius: var(--ek-radius-md);
          font-family: var(--ek-font-body);
          font-size: 15px;
          font-weight: 500;
          color: var(--ek-text);
          background: var(--ek-surface-2);
          outline: none;
          transition: border-color 0.18s, box-shadow 0.18s, background 0.18s;
        }

        .ek-search-input::placeholder {
          color: var(--ek-text-mute);
          font-weight: 400;
        }

        .ek-search-input:focus {
          border-color: var(--ek-orange);
          background: white;
          box-shadow: 0 0 0 4px rgba(247, 148, 30, 0.14);
        }

        .ek-search-input:disabled {
          opacity: 0.6;
          cursor: not-allowed;
        }

        .ek-btn-verify {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          gap: 8px;
          padding: 14px 28px;
          border: none;
          border-radius: var(--ek-radius-md);
          background: linear-gradient(135deg, var(--ek-orange) 0%, var(--ek-orange-dark) 100%);
          color: white;
          font-family: var(--ek-font-display);
          font-size: 15px;
          font-weight: 700;
          letter-spacing: 0.01em;
          cursor: pointer;
          white-space: nowrap;
          transition: transform 0.15s, box-shadow 0.18s, filter 0.18s;
          box-shadow: 0 4px 14px -2px rgba(247, 148, 30, 0.45);
        }

        .ek-btn-verify:hover:not(:disabled) {
          filter: brightness(1.05);
          box-shadow: 0 8px 22px -4px rgba(247, 148, 30, 0.55);
          transform: translateY(-1px);
        }

        .ek-btn-verify:active:not(:disabled) {
          transform: translateY(0);
        }

        .ek-btn-verify:disabled {
          background: #cbd5dc;
          cursor: not-allowed;
          box-shadow: none;
        }

        .ek-search-hint {
          font-size: 12px;
          color: var(--ek-text-mute);
          display: flex;
          align-items: center;
          gap: 6px;
          flex-wrap: wrap;
        }

        .ek-search-hint code {
          font-family: 'JetBrains Mono', 'Courier New', monospace;
          font-size: 11px;
          font-weight: 700;
          color: var(--ek-navy);
          padding: 2px 8px;
          background: rgba(30, 58, 110, 0.08);
          border-radius: 5px;
          letter-spacing: 0.02em;
        }

        /* ─── States ───────────────────────────────────────────────── */
        .ek-loading {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 16px;
          padding: 48px 24px;
          color: var(--ek-text-mute);
          font-size: 14px;
          animation: ekFadeUp 0.4s ease both;
        }

        .ek-spinner {
          width: 36px;
          height: 36px;
          border-radius: 50%;
          border: 3px solid rgba(247, 148, 30, 0.18);
          border-top-color: var(--ek-orange);
          animation: ekSpin 0.75s linear infinite;
        }

        @keyframes ekSpin { to { transform: rotate(360deg); } }
        @keyframes ekFadeUp {
          from { opacity: 0; transform: translateY(12px); }
          to   { opacity: 1; transform: translateY(0); }
        }

        .ek-error {
          display: flex;
          gap: 14px;
          align-items: flex-start;
          padding: 20px 24px;
          background: var(--ek-error-bg);
          border: 1px solid rgba(220, 38, 38, 0.25);
          border-radius: var(--ek-radius-lg);
          animation: ekFadeUp 0.4s ease both;
        }

        .ek-error-icon {
          flex-shrink: 0;
          width: 22px;
          height: 22px;
          color: var(--ek-error);
          margin-top: 1px;
        }

        .ek-error-body {
          font-size: 14px;
          line-height: 1.55;
          color: #7f1d1d;
        }

        .ek-error-body strong {
          display: block;
          font-family: var(--ek-font-display);
          font-weight: 700;
          margin-bottom: 3px;
          color: #991b1b;
        }

        /* ─── Certificate card ─────────────────────────────────────── */
        .ek-cert-card {
          background: var(--ek-surface);
          border: 1px solid var(--ek-border);
          border-radius: var(--ek-radius-xl);
          box-shadow: var(--ek-shadow-xl);
          overflow: hidden;
          animation: ekCertIn 0.5s cubic-bezier(0.16, 1, 0.3, 1) both;
        }

        @keyframes ekCertIn {
          from { opacity: 0; transform: translateY(20px) scale(0.98); }
          to   { opacity: 1; transform: translateY(0) scale(1); }
        }

        .ek-cert-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 12px;
          flex-wrap: wrap;
          padding: 18px 26px;
          background: var(--ek-navy);
          color: white;
        }

        .ek-cert-header-left {
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .ek-cert-badge-icon {
          width: 32px;
          height: 32px;
          border-radius: 9px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: linear-gradient(135deg, var(--ek-orange) 0%, var(--ek-orange-light) 100%);
          color: white;
          box-shadow: 0 2px 8px -2px rgba(247, 148, 30, 0.6);
        }

        .ek-cert-header-title {
          font-family: var(--ek-font-display);
          font-size: 14px;
          font-weight: 700;
          color: white;
          letter-spacing: 0.01em;
        }

        .ek-cert-serial {
          font-family: 'JetBrains Mono', 'Courier New', monospace;
          font-size: 12px;
          font-weight: 600;
          color: var(--ek-orange-light);
          padding: 5px 12px;
          background: rgba(255, 255, 255, 0.08);
          border: 1px solid rgba(255, 255, 255, 0.12);
          border-radius: 8px;
          letter-spacing: 0.03em;
        }

        .ek-cert-hero {
          text-align: center;
          padding: 36px 26px 28px;
          background: linear-gradient(180deg, #fbfcfe 0%, #ffffff 100%);
        }

        .ek-cert-hero-eyebrow {
          font-size: 11px;
          font-weight: 700;
          letter-spacing: 0.22em;
          text-transform: uppercase;
          color: var(--ek-text-mute);
          margin-bottom: 12px;
        }

        .ek-cert-hero-name {
          font-family: var(--ek-font-display);
          font-size: clamp(30px, 6vw, 44px);
          font-weight: 800;
          letter-spacing: -0.03em;
          line-height: 1.1;
          color: var(--ek-navy);
          margin-bottom: 10px;
        }

        .ek-cert-hero-sub {
          font-size: 14px;
          color: var(--ek-text-2);
          font-weight: 500;
        }

        .ek-cert-divider {
          height: 1px;
          background: var(--ek-border);
          margin: 0 26px;
        }

        .ek-cert-info {
          display: flex;
          flex-direction: column;
          padding: 20px 26px;
        }

        .ek-info-row {
          display: flex;
          justify-content: space-between;
          align-items: baseline;
          gap: 18px;
          padding: 12px 0;
          border-bottom: 1px dashed var(--ek-border);
        }

        .ek-info-row:last-child {
          border-bottom: none;
        }

        .ek-info-label {
          font-size: 11px;
          font-weight: 700;
          letter-spacing: 0.10em;
          text-transform: uppercase;
          color: var(--ek-text-mute);
          flex-shrink: 0;
        }

        .ek-info-value {
          font-size: 14px;
          font-weight: 500;
          color: var(--ek-text);
          text-align: right;
          line-height: 1.4;
        }

        .ek-info-value--hl {
          color: var(--ek-orange-dark);
          font-weight: 700;
        }

        .ek-cert-footer {
          display: flex;
          align-items: center;
          justify-content: space-between;
          flex-wrap: wrap;
          gap: 12px;
          padding: 20px 26px;
          background: var(--ek-surface-2);
          border-top: 1px solid var(--ek-border);
        }

        .ek-status-chip {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          padding: 6px 14px;
          font-size: 12px;
          font-weight: 600;
          color: var(--ek-success);
          background: var(--ek-success-bg);
          border-radius: 100px;
        }

        .ek-status-dot {
          width: 6px;
          height: 6px;
          border-radius: 50%;
          background: var(--ek-success);
          box-shadow: 0 0 0 0 rgba(22, 163, 74, 0.5);
          animation: ekPulse 2s ease-in-out infinite;
        }

        @keyframes ekPulse {
          0%, 100% { box-shadow: 0 0 0 0 rgba(22, 163, 74, 0.5); }
          50%      { box-shadow: 0 0 0 6px rgba(22, 163, 74, 0); }
        }

        .ek-btn-download {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          padding: 11px 22px;
          background: var(--ek-navy);
          color: white;
          font-family: var(--ek-font-display);
          font-size: 13px;
          font-weight: 700;
          text-decoration: none;
          border-radius: var(--ek-radius-md);
          letter-spacing: 0.01em;
          transition: background 0.18s, transform 0.12s, box-shadow 0.18s;
          box-shadow: 0 2px 8px rgba(30, 58, 110, 0.22);
        }

        .ek-btn-download:hover {
          background: var(--ek-navy-dark);
          transform: translateY(-1px);
          box-shadow: 0 6px 16px rgba(30, 58, 110, 0.32);
        }

        .ek-btn-download:active {
          transform: translateY(0);
        }

        /* ─── Reset ────────────────────────────────────────────────── */
        .ek-reset {
          align-self: center;
          padding: 8px 16px;
          background: none;
          border: none;
          font-family: var(--ek-font-body);
          font-size: 13px;
          font-weight: 600;
          color: var(--ek-text-2);
          cursor: pointer;
          text-decoration: underline;
          text-underline-offset: 4px;
          text-decoration-color: var(--ek-border-2);
          transition: color 0.18s, text-decoration-color 0.18s;
        }

        .ek-reset:hover {
          color: var(--ek-orange-dark);
          text-decoration-color: var(--ek-orange);
        }

        /* ─── Footer ───────────────────────────────────────────────── */
        .ek-footer {
          text-align: center;
          font-size: 12px;
          color: var(--ek-text-mute);
          line-height: 1.7;
          max-width: 400px;
          margin: 8px auto 0;
        }

        .ek-footer strong {
          color: var(--ek-navy);
          font-weight: 700;
        }

        /* ─── Responsive ───────────────────────────────────────────── */
        @media (min-width: 768px) {
          .ek-shell { padding: 64px 32px 88px; }
        }

        @media (max-width: 520px) {
          .ek-shell { padding: 32px 16px 56px; }
          .ek-container { gap: 26px; }
          .ek-search { padding: 22px 20px; }
          .ek-search-row { flex-direction: column; }
          .ek-btn-verify { width: 100%; padding: 15px; }
          .ek-cert-header { padding: 16px 20px; }
          .ek-cert-hero { padding: 28px 20px 22px; }
          .ek-cert-divider { margin: 0 20px; }
          .ek-cert-info { padding: 16px 20px; }
          .ek-info-row {
            flex-direction: column;
            gap: 4px;
            align-items: flex-start;
          }
          .ek-info-value { text-align: left; }
          .ek-cert-footer {
            flex-direction: column;
            align-items: stretch;
            padding: 18px 20px;
          }
          .ek-btn-download { justify-content: center; }
          .ek-logo { padding: 10px 16px; gap: 10px; }
          .ek-logo-mark { width: 36px; height: 36px; }
          .ek-logo-name { font-size: 17px; }
          .ek-logo-sub { font-size: 9px; letter-spacing: 0.22em; }
          .ek-logo-sub::before,
          .ek-logo-sub::after { width: 12px; }
        }

        @media print {
          .ek-search, .ek-reset, .ek-footer, .ek-brand, .ek-hero { display: none; }
          .ek-shell { padding: 0; }
          .ek-cert-card { box-shadow: none; border: 1px solid #ccc; }
          .ek-root::before { display: none; }
        }
      `}</style>

      <div className="ek-root">
        <div className="ek-shell">
          <div className="ek-container">

            {/* Brand logo */}
            <div className="ek-brand">
              <div className="ek-logo">
                <div className="ek-logo-mark">
                  {/* EzyKnot logo recreation — swirl + arrow */}
                  <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                    <defs>
                      <linearGradient id="ek-swirl-blue" x1="0%" y1="0%" x2="100%" y2="100%">
                        <stop offset="0%" stopColor="#1B75BC" />
                        <stop offset="100%" stopColor="#1E3A6E" />
                      </linearGradient>
                      <linearGradient id="ek-swirl-orange" x1="0%" y1="100%" x2="100%" y2="0%">
                        <stop offset="0%" stopColor="#F7941E" />
                        <stop offset="100%" stopColor="#FBB040" />
                      </linearGradient>
                      <linearGradient id="ek-swirl-green" x1="0%" y1="100%" x2="0%" y2="0%">
                        <stop offset="0%" stopColor="#7AB947" />
                        <stop offset="100%" stopColor="#FBB040" />
                      </linearGradient>
                    </defs>
                    {/* Blue swirl */}
                    <path
                      d="M15 65 Q15 30 45 30 Q65 30 65 48 Q65 62 50 62 Q40 62 40 52 Q40 45 47 45"
                      fill="none"
                      stroke="url(#ek-swirl-blue)"
                      strokeWidth="7"
                      strokeLinecap="round"
                    />
                    {/* Red-orange swirl */}
                    <path
                      d="M8 72 Q22 78 40 72 Q60 65 65 55"
                      fill="none"
                      stroke="#E85D2C"
                      strokeWidth="6"
                      strokeLinecap="round"
                    />
                    {/* Green to orange swirl */}
                    <path
                      d="M20 78 Q40 82 58 72 Q72 62 78 42"
                      fill="none"
                      stroke="url(#ek-swirl-green)"
                      strokeWidth="6"
                      strokeLinecap="round"
                    />
                    {/* Orange arrow */}
                    <path
                      d="M55 78 Q68 68 80 45"
                      fill="none"
                      stroke="url(#ek-swirl-orange)"
                      strokeWidth="6"
                      strokeLinecap="round"
                    />
                    <path
                      d="M80 45 L72 42 M80 45 L78 54"
                      fill="none"
                      stroke="url(#ek-swirl-orange)"
                      strokeWidth="6"
                      strokeLinecap="round"
                    />
                  </svg>
                </div>
                <div className="ek-logo-text">
                  <span className="ek-logo-name">
                    Ezy<span className="ek-logo-knot">Knot</span>
                  </span>
                  <span className="ek-logo-sub">Careers</span>
                </div>
              </div>
            </div>

            {/* Hero */}
            <div className="ek-hero">
              <h1>
                Verify a <em>Certificate</em>
              </h1>
              <p>
                Enter the certificate serial number to confirm authenticity
                and view the full credential details.
              </p>
            </div>

            {/* Search */}
            <div className="ek-search">
              <label htmlFor="ek-slno" className="ek-search-label">
                Certificate Serial Number
              </label>
              <div className="ek-search-row">
                <div className="ek-input-wrap">
                  <span className="ek-input-icon">
                    <IconSearch />
                  </span>
                  <input
                    id="ek-slno"
                    className="ek-search-input"
                    type="text"
                    placeholder="EKC/UTK0107"
                    value={inputValue}
                    onChange={(e) => setInputValue(e.target.value)}
                    onKeyDown={handleKeyDown}
                    disabled={loading}
                    autoComplete="off"
                    spellCheck={false}
                  />
                </div>
                <button
                  className="ek-btn-verify"
                  type="button"
                  onClick={handleVerify}
                  disabled={loading || !inputValue.trim()}
                >
                  {loading ? "Checking…" : "Verify"}
                </button>
              </div>
              <p className="ek-search-hint">
                The serial number is printed on your certificate — format
                <code>EK/YY/###</code>
              </p>
            </div>

            {/* Loading */}
            {loading && (
              <div className="ek-loading">
                <div className="ek-spinner" />
                <span>Fetching certificate details…</span>
              </div>
            )}

            {/* Error */}
            {!loading && error && (
              <div className="ek-error">
                <svg
                  className="ek-error-icon"
                  viewBox="0 0 24 24"
                  fill="none"
                  aria-hidden="true"
                >
                  <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="1.8" />
                  <path
                    d="M12 8v4M12 16h.01"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                  />
                </svg>
                <div className="ek-error-body">
                  <strong>Certificate not found</strong>
                  {error}. Please double-check the serial number and try again.
                </div>
              </div>
            )}

            {/* Certificate */}
            {!loading && certificate && (
              <>
                <CertificateCard cert={certificate} />
                <button className="ek-reset" onClick={handleReset}>
                  Verify another certificate
                </button>
              </>
            )}

            {/* Footer */}
            <p className="ek-footer">
              This verification page is maintained by <strong>EzyKnot Careers</strong>.
              <br />
              Certificate data is fetched in real-time from secure records.
            </p>

          </div>
        </div>
      </div>
    </>
  );
}
